### ISSUE TITLE
Add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by Zanark** [Zanark/Handy-Scriptz#11]
The file should contain the following rules

- Commit to a new branch
- Follow CamelCase naming convention
- Add PHP scripts to the PHP folder
- Do not commit framework initiated files.

_The issue is still open to everyone. It has not been assigned to anyone yet_

**Comment by prajaktagadhave** [comment]
I am on it!

**Comment by Zanark** [comment]
@prajaktagadhave great
